source 'http://ruby.taobao.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# API
gem "grape", "~> 0.3.1"
gem "grape-entity", "~> 0.2.0"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby
  gem "less-rails"
  gem "twitter-bootstrap-rails"
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'devise', '>= 2.2.3'
gem 'ffi', '1.7.0'
gem 'vagrant', :git => 'git://github.com/mitchellh/vagrant.git', :tag => 'v1.2.2'
gem "friendly_id", "~> 4.0.9"
gem "settingslogic", "~> 2.0.9"
gem 'seed-fu', '2.2.0'
gem 'sidekiq', '~> 2.11.2'
gem "rest-client", "~> 1.6.7"
gem 'redis', "~> 3.0.4"

group :development, :test do
  gem 'debugger'
  gem 'pry-rails'
  gem 'capistrano', '~> 2.14.2'
  gem 'thin'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'
